#!/usr/bin/env python3
"""
AI Test Generator
Generates comprehensive xUnit tests from specifications and code.
"""

import json
import argparse
from pathlib import Path
from datetime import datetime, UTC

# Load config first (handles .env loading)
import config

from openai import OpenAI

client = OpenAI()  # Uses OPENAI_API_KEY from environment

SYSTEM_PROMPT = """You are a QA engineer at Glow Financial Services.
Generate comprehensive pytest tests for Python Flask code.

TEST CATEGORIES TO GENERATE:
1. Happy path tests (valid inputs → expected outputs)
2. Boundary tests (edge cases at limits)
3. Negative tests (invalid inputs → proper error handling)
4. Decision rule tests (each rule path covered)
5. Compliance tests (audit logging, PII handling)

REQUIREMENTS:
- Use pytest with clear test names
- Use pytest fixtures for setup
- Each test must have a clear Arrange/Act/Assert structure
- Test names: test_method_scenario_expected_result
- Use @pytest.mark.parametrize for parameterized tests
- Aim for >90% code coverage
- Test all decision rule branches"""

def load_spec(filepath: str) -> dict:
    with open(filepath, 'r') as f:
        return json.load(f)

def load_code(directory: str) -> str:
    code_dir = Path(directory)
    code_content = ""
    for py_file in code_dir.glob("*.py"):
        with open(py_file, 'r') as f:
            code_content += f"\n# === {py_file.name} ===\n"
            code_content += f.read()
    return code_content

def generate_tests(spec: dict, code: str) -> str:
    """Generate comprehensive test suite."""

    # Calculate test cases needed
    decision_rules = spec.get("decision_rules", [])
    inputs = spec.get("inputs", [])

    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": f"""Generate pytest tests for this specification and code:

SPECIFICATION:
{json.dumps(spec, indent=2)}

CODE:
{code}

Generate tests for:
1. Each decision rule ({len(decision_rules)} rules)
2. Input validation for each field ({len(inputs)} inputs)
3. Boundary conditions
4. Error scenarios
5. Audit logging verification

Output only Python pytest code, no markdown, no explanations."""}
        ],
        temperature=0.2
    )

    return response.choices[0].message.content

def generate_golden_tests(spec: dict) -> list:
    """Generate golden test cases for regression testing."""

    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": "Generate golden test cases as JSON for prompt regression testing."},
            {"role": "user", "content": f"""Create golden test cases for this specification:

{json.dumps(spec, indent=2)}

Output JSON array with format:
[
  {{
    "name": "test_name",
    "input": {{}},
    "expected_output": {{}},
    "expected_reason_code": "..."
  }}
]

Include edge cases and all decision paths."""}
        ],
        response_format={"type": "json_object"},
        temperature=0.1
    )

    result = json.loads(response.choices[0].message.content)
    return result.get("test_cases", result.get("tests", [result]))

def strip_markdown_fences(code: str) -> str:
    """Remove markdown code fences from LLM-generated code."""
    lines = code.strip().split('\n')

    # Remove opening code fence (```csharp, ```cs, or just ```)
    if lines and lines[0].strip().startswith('```'):
        lines = lines[1:]

    # Remove closing code fence
    if lines and lines[-1].strip() == '```':
        lines = lines[:-1]

    return '\n'.join(lines)

def main():
    parser = argparse.ArgumentParser(description="Generate tests from spec and code")
    parser.add_argument("--spec", required=True, help="Specification JSON file")
    parser.add_argument("--code", required=True, help="Generated code directory")
    parser.add_argument("--output", required=True, help="Output directory")
    args = parser.parse_args()
    
    print(f"📋 Loading specification: {args.spec}")
    spec = load_spec(args.spec)
    
    print(f"📂 Loading code from: {args.code}")
    code = load_code(args.code)
    
    print("🧪 Generating unit tests...")
    tests = generate_tests(spec, code)
    
    print("🎯 Generating golden test cases...")
    golden_tests = generate_golden_tests(spec)
    
    # Save
    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    header = f"""# <auto-generated>
# Generated by Glow AI Test Generator
# Timestamp: {datetime.now(UTC).isoformat()}
# </auto-generated>

"""

    # Strip markdown fences from generated test code
    tests = strip_markdown_fences(tests)

    tests_file = output_dir / "test_api.py"
    with open(tests_file, 'w') as f:
        f.write(header + tests)
    print(f"💾 Tests saved: {tests_file}")
    
    golden_file = output_dir / "golden_tests.json"
    with open(golden_file, 'w') as f:
        json.dump(golden_tests, f, indent=2)
    print(f"💾 Golden tests saved: {golden_file}")
    
    print(f"\n✅ Test generation complete")
    print(f"   - Test file: {tests_file}")
    print(f"   - Golden tests: {len(golden_tests)} cases")

if __name__ == "__main__":
    main()
