#!/usr/bin/env python3
"""
Specification → Code Generator
Generates production C# code from structured specifications.
"""

import json
import argparse
from pathlib import Path
from datetime import datetime, UTC

# Load config first (handles .env loading)
import config

from openai import OpenAI

client = OpenAI()  # Uses OPENAI_API_KEY from environment

SYSTEM_PROMPT = """You are a senior Python developer at Glow Financial Services.
Generate production-ready Python Flask API code from specifications.

REQUIREMENTS:
1. Use Flask with type hints
2. Include proper audit logging for every decision
3. All business logic must be deterministic and traceable
4. Use dataclasses for models
5. Include docstrings
6. Use proper exception handling
7. PII fields must never be logged directly
8. All decision paths must have reason codes

OUTPUT FORMAT:
Generate a complete Flask application with:
- Flask Blueprint with proper routing
- Request/response models using dataclasses
- Input validation using marshmallow or pydantic
- Business logic implementation
- Audit logging
- Clean, testable code"""

CODE_TEMPLATE = '''
// <auto-generated>
// Generated by Glow AI Pipeline
// Timestamp: {timestamp}
// Source Spec: {spec_id}
// DO NOT EDIT MANUALLY
// </auto-generated>

using Microsoft.AspNetCore.Mvc;
using Glow.Claims.Api.Models;
using Glow.Claims.Api.Services;
using Glow.Claims.Api.Audit;

namespace Glow.Claims.Api.Controllers;

/// <summary>
/// {description}
/// </summary>
[ApiController]
[Route("{route}")]
public class {class_name} : ControllerBase
{{
    private readonly IClaimService _claimService;
    private readonly IAuditLogger _auditLogger;
    private readonly ILogger<{class_name}> _logger;

    public {class_name}(
        IClaimService claimService,
        IAuditLogger auditLogger,
        ILogger<{class_name}> logger)
    {{
        _claimService = claimService;
        _auditLogger = auditLogger;
        _logger = logger;
    }}

{methods}
}}
'''

def load_spec(filepath: str) -> dict:
    """Load specification from JSON file."""
    with open(filepath, 'r') as f:
        return json.load(f)

def generate_code(spec: dict) -> str:
    """Use LLM to generate Python Flask code from specification."""

    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": f"""Generate Python Flask API code for this specification:

{json.dumps(spec, indent=2)}

Include:
1. Request/Response models using dataclasses
2. Flask Blueprint with proper routing
3. Business logic implementing ALL decision rules
4. Audit logging for every decision
5. Input validation

Output only the Python code, no markdown, no explanations."""}
        ],
        temperature=0.1
    )

    return response.choices[0].message.content

def generate_models(spec: dict) -> str:
    """Generate Python model classes."""

    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": "Generate Python dataclass models with validation using pydantic. Include docstrings."},
            {"role": "user", "content": f"""Generate request/response models for:

Inputs: {json.dumps(spec['inputs'], indent=2)}
Outputs: {json.dumps(spec['outputs'], indent=2)}

Use pydantic BaseModel with validators. Output only Python code, no markdown."""}
        ],
        temperature=0.1
    )

    return response.choices[0].message.content

def strip_markdown_fences(code: str) -> str:
    """Remove markdown code fences from LLM-generated code."""
    lines = code.strip().split('\n')

    # Remove opening code fence (```csharp, ```cs, or just ```)
    if lines and lines[0].strip().startswith('```'):
        lines = lines[1:]

    # Remove closing code fence
    if lines and lines[-1].strip() == '```':
        lines = lines[:-1]

    return '\n'.join(lines)

def main():
    parser = argparse.ArgumentParser(description="Generate code from specification")
    parser.add_argument("--spec", required=True, help="Specification JSON file")
    parser.add_argument("--template", help="Optional Jinja2 template")
    parser.add_argument("--output", required=True, help="Output directory")
    args = parser.parse_args()
    
    # Load spec
    print(f"📋 Loading specification: {args.spec}")
    spec = load_spec(args.spec)
    
    # Generate code
    print("⚡ Generating C# controller code...")
    controller_code = generate_code(spec)
    
    print("⚡ Generating C# models...")
    models_code = generate_models(spec)
    
    # Save
    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Add generation header
    header = f"""# <auto-generated>
# Generated by Glow AI Pipeline
# Timestamp: {datetime.now(UTC).isoformat()}
# Spec: {spec.get('_metadata', {}).get('source_prd', 'unknown')}
# </auto-generated>

"""

    # Strip markdown fences from generated code
    controller_code = strip_markdown_fences(controller_code)
    models_code = strip_markdown_fences(models_code)

    api_file = output_dir / "api.py"
    with open(api_file, 'w') as f:
        f.write(header + controller_code)
    print(f"💾 API saved: {api_file}")

    models_file = output_dir / "models.py"
    with open(models_file, 'w') as f:
        f.write(header + models_code)
    print(f"💾 Models saved: {models_file}")
    
    print(f"\n✅ Code generation complete")
    print(f"   - API: {spec['api_contract']['method']} {spec['api_contract']['endpoint']}")
    print(f"   - Rules implemented: {len(spec['decision_rules'])}")

if __name__ == "__main__":
    main()
