#!/usr/bin/env python3
"""
Specification → Code Generator
Generates production C# code from structured specifications.
"""

import json
import argparse
from pathlib import Path
from datetime import datetime, UTC

# Load config first (handles .env loading)
import config

from openai import OpenAI

client = OpenAI()  # Uses OPENAI_API_KEY from environment

SYSTEM_PROMPT = """You are a senior .NET developer at Glow Financial Services.
Generate production-ready C# code from specifications.

REQUIREMENTS:
1. Use .NET 8 / ASP.NET Core
2. Include proper audit logging for every decision
3. All business logic must be deterministic and traceable
4. Follow SOLID principles
5. Include XML documentation
6. Use proper exception handling
7. PII fields must never be logged directly
8. All decision paths must have reason codes

OUTPUT FORMAT:
Generate a complete controller class with:
- Proper attributes and routing
- Input validation
- Business logic implementation
- Audit logging integration
- Unit-testable design (use interfaces)

Use these exact namespaces:
- Glow.Claims.Api.Controllers
- Glow.Claims.Api.Models
- Glow.Claims.Api.Services
- Glow.Claims.Api.Audit"""

CODE_TEMPLATE = '''
// <auto-generated>
// Generated by Glow AI Pipeline
// Timestamp: {timestamp}
// Source Spec: {spec_id}
// DO NOT EDIT MANUALLY
// </auto-generated>

using Microsoft.AspNetCore.Mvc;
using Glow.Claims.Api.Models;
using Glow.Claims.Api.Services;
using Glow.Claims.Api.Audit;

namespace Glow.Claims.Api.Controllers;

/// <summary>
/// {description}
/// </summary>
[ApiController]
[Route("{route}")]
public class {class_name} : ControllerBase
{{
    private readonly IClaimService _claimService;
    private readonly IAuditLogger _auditLogger;
    private readonly ILogger<{class_name}> _logger;

    public {class_name}(
        IClaimService claimService,
        IAuditLogger auditLogger,
        ILogger<{class_name}> logger)
    {{
        _claimService = claimService;
        _auditLogger = auditLogger;
        _logger = logger;
    }}

{methods}
}}
'''

def load_spec(filepath: str) -> dict:
    """Load specification from JSON file."""
    with open(filepath, 'r') as f:
        return json.load(f)

def generate_code(spec: dict) -> str:
    """Use LLM to generate C# code from specification."""
    
    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": f"""Generate C# controller code for this specification:

{json.dumps(spec, indent=2)}

Include:
1. Request/Response models
2. Controller with proper routing
3. Business logic implementing ALL decision rules
4. Audit logging for every decision
5. Input validation attributes

Output only the C# code, no markdown."""}
        ],
        temperature=0.1
    )
    
    return response.choices[0].message.content

def generate_models(spec: dict) -> str:
    """Generate C# model classes."""
    
    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": "Generate C# model classes with data annotations for validation. Include XML documentation."},
            {"role": "user", "content": f"""Generate request/response models for:

Inputs: {json.dumps(spec['inputs'], indent=2)}
Outputs: {json.dumps(spec['outputs'], indent=2)}

Namespace: Glow.Claims.Api.Models"""}
        ],
        temperature=0.1
    )
    
    return response.choices[0].message.content

def main():
    parser = argparse.ArgumentParser(description="Generate code from specification")
    parser.add_argument("--spec", required=True, help="Specification JSON file")
    parser.add_argument("--template", help="Optional Jinja2 template")
    parser.add_argument("--output", required=True, help="Output directory")
    args = parser.parse_args()
    
    # Load spec
    print(f"📋 Loading specification: {args.spec}")
    spec = load_spec(args.spec)
    
    # Generate code
    print("⚡ Generating C# controller code...")
    controller_code = generate_code(spec)
    
    print("⚡ Generating C# models...")
    models_code = generate_models(spec)
    
    # Save
    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Add generation header
    header = f"""// <auto-generated>
// Generated by Glow AI Pipeline
// Timestamp: {datetime.now(UTC).isoformat()}
// Spec: {spec.get('_metadata', {}).get('source_prd', 'unknown')}
// </auto-generated>

"""
    
    controller_file = output_dir / "ClaimsController.cs"
    with open(controller_file, 'w') as f:
        f.write(header + controller_code)
    print(f"💾 Controller saved: {controller_file}")
    
    models_file = output_dir / "Models.cs"
    with open(models_file, 'w') as f:
        f.write(header + models_code)
    print(f"💾 Models saved: {models_file}")
    
    print(f"\n✅ Code generation complete")
    print(f"   - API: {spec['api_contract']['method']} {spec['api_contract']['endpoint']}")
    print(f"   - Rules implemented: {len(spec['decision_rules'])}")

if __name__ == "__main__":
    main()
